development:
  adapter: postgresql
  encoding: utf8
  database: personal_development
  pool: 5
  username: kaizeras
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: personal_test
  pool: 5
  username: kaizeras
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: personal_production
  pool: 5
  username: kaizeras
  password: